import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import Footer from '../../components/footer'


const Home: NextPage = () => {
    const [totalValue, setTotalValue] = useState<number>()
    const [entryValue, setEntryValue] = useState<number>()
    const [missingValue, setMisingValue] = useState<number>()
    const taxas = [3.75, 4.90, 5.40, 5.90, 6.40, 6.80, 7.70, 8.20, 8.70, 9.20, 9.70, 10.20];
    useEffect(() => {
        const value = totalValue ?  totalValue - (entryValue ? entryValue : 0) : 0
        setMisingValue(value)
    }, [totalValue, entryValue])
  return (
    <div style={{display:'flex', width: '100%', alignItems: 'center', flexDirection: 'column', minHeight: '100vh'}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{display:'flex', width: '100%', alignItems: 'center', flexDirection: 'column', padding: '20px'}}>
        <input style={{padding: '12px', margin: '12px'}} placeholder="R$ 0,00" type="number" value={totalValue} onChange={(e) => setTotalValue(parseInt(e.target.value))} />
        <input style={{padding: '12px'}} type="number" placeholder="R$ 0,00" value={entryValue} onChange={(e) => setEntryValue(parseInt(e.target.value))}/>
      </div>

      {totalValue && 
      <div style={{display:'flex', width: '100%', justifyContent:'center'}}>
        <table>
            <thead >
                <tr >
                    <th style={{padding: '8px', fontSize: '.85rem'}}>PARCELAS</th>
                    <th style={{padding: '8px', fontSize: '.85rem'}}>VALOR DAS PARCELAS</th>
                    <th style={{padding: '8px', fontSize: '.85rem'}}>VALOR TOTAL</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td style={{padding: '8px', fontSize: '.85rem', textAlign: 'left'}}>À VISTA</td>
                    <td style={{padding: '8px', fontSize: '.85rem', textAlign: 'center'}}>SEM PARCELAR</td>
                    <td style={{padding: '8px', fontSize: '.85rem', textAlign: 'right'}}>{totalValue.toLocaleString('pt-br', {style: 'currency', currency: 'BRL'})}</td>
                </tr>

                {taxas.map((taxa: number, index: number) => {
                    const percentage = (taxa * (missingValue ? missingValue : 0)) / 100
                    const newTotalValue = totalValue + percentage
                    const valuePerMonth = (newTotalValue / (index + 1))
                    if (index === 0 && (entryValue === 0 || entryValue === undefined)) {
                        return null
                    }
                return (
                    <tr key={index}>
                        <td style={{padding: '8px', fontSize: '.85rem', textAlign: 'left'}}>{index + 1} X</td>
                        <td style={{padding: '8px', fontSize: '.85rem', textAlign: 'center'}}>{(index === 0 ? valuePerMonth - (entryValue ? entryValue : 0) : valuePerMonth).toLocaleString('pt-br', {style: 'currency', currency: 'BRL'})}</td>
                        <td style={{padding: '8px', fontSize: '.85rem', textAlign: 'right'}}>{newTotalValue.toLocaleString('pt-br', {style: 'currency', currency: 'BRL'})}</td>
                    </tr>
                )  
                })}
            </tbody>
        </table>

      </div>}
      
    </div>

  )
}

export default Home