import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Footer from '../components/footer'
import Header from '../components/header'
import List from '../components/list'
import Navbar from '../components/navbar'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Navbar />
      <List />
      <div style={{display: 'flex', justifyContent: 'center',  alignItems: 'center', width: '100%', backgroundColor: '#4162e1', color: 'white', borderRadius: '20px', padding: '12px', marginTop: '24px'}}>
        <Link href='/simulate' >
          Simular pagamentos
        </Link>
      </div>
      <Footer />

    </div>

  )
}

export default Home
